version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weather-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@weather.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - weather-net

  etl:
    build: ./
    container_name: weather-etl
    depends_on:
      - postgres
    networks:
      - weather-net
    env_file:
      - .env

volumes:
  pgdata:

networks:
  weather-net:
    driver: bridge
